
import { useLocation } from "react-router-dom";
import { Link } from "react-router-dom";
import PageLayout from "../components/layout/PageLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Target, Zap, TrendingUp, Users, Shield } from "lucide-react";
import { Helmet } from "react-helmet-async";

const AIAndDigitalMarketing = () => {
  const location = useLocation();

  const aiMarketingAreas = [
    {
      id: 1,
      title: "AI-Powered Ad Targeting",
      description: "Machine learning algorithms that analyze user behavior and demographics to deliver personalized advertising experiences.",
      example: "Dynamic audience segmentation and predictive targeting based on user journey analysis.",
      benefit: "Up to 40% improvement in conversion rates through precision targeting.",
      icon: <Target className="h-6 w-6 text-blue-400" />,
      link: "/ad-funnel-blueprint"
    },
    {
      id: 2,
      title: "Generative Content Creation",
      description: "AI systems that create marketing copy, images, and video content tailored to specific audiences and campaigns.",
      example: "Automated A/B testing of ad creative variations generated by AI for different market segments.",
      benefit: "70% reduction in content creation time while maintaining quality and relevance.",
      icon: <Brain className="h-6 w-6 text-purple-400" />,
      link: "/resources/content-creation-agent"
    },
    {
      id: 3,
      title: "Predictive Analytics",
      description: "Advanced analytics that forecast customer behavior, campaign performance, and market trends.",
      example: "Customer lifetime value prediction and churn prevention through behavioral pattern analysis.",
      benefit: "25% increase in customer retention through proactive engagement strategies.",
      icon: <TrendingUp className="h-6 w-6 text-green-400" />,
      link: "/technical"
    },
    {
      id: 4,
      title: "Real-Time Optimization",
      description: "AI systems that continuously adjust campaigns based on performance data and market conditions.",
      example: "Automatic bid adjustments and budget reallocation across channels for maximum ROI.",
      benefit: "30% improvement in campaign efficiency through continuous optimization.",
      icon: <Zap className="h-6 w-6 text-yellow-400" />,
      link: "/generative-engine-optimization"
    },
    {
      id: 5,
      title: "Customer Journey Mapping",
      description: "AI-driven analysis of customer touchpoints to optimize the entire marketing funnel.",
      example: "Personalized content delivery at each stage of the customer journey based on behavior signals.",
      benefit: "50% improvement in lead quality through optimized customer experience paths.",
      icon: <Users className="h-6 w-6 text-cyan-400" />,
      link: "/answer-engine-optimization"
    },
    {
      id: 6,
      title: "Ethical AI Implementation",
      description: "Responsible AI practices that ensure fair and transparent marketing while protecting user privacy.",
      example: "Bias detection systems and privacy-first targeting that builds consumer trust.",
      benefit: "Enhanced brand reputation and compliance with evolving data protection regulations.",
      icon: <Shield className="h-6 w-6 text-emerald-400" />,
      link: "/ai-bias-in-advertising"
    },
  ];

  return (
    <PageLayout 
      title="AI & Digital Marketing Revolution"
      subtitle="Transforming marketing strategies through artificial intelligence and machine learning technologies"
      currentPath={location.pathname}
    >
      <Helmet>
        <title>AI & Digital Marketing | AI-Powered Marketing Solutions | Digital Frontier</title>
        <meta name="description" content="Discover how AI is revolutionizing digital marketing. Learn about AI-powered targeting, content creation, predictive analytics, and ethical AI implementation." />
        <meta name="keywords" content="AI marketing, artificial intelligence, digital marketing AI, machine learning marketing, AI advertising, marketing automation" />
        
        {/* Article Schema */}
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": "AI & Digital Marketing Revolution",
            "description": "Transforming marketing strategies through artificial intelligence and machine learning technologies",
            "author": {
              "@type": "Organization",
              "name": "Digital Frontier Company"
            },
            "publisher": {
              "@type": "Organization",
              "name": "Digital Frontier Company",
              "logo": {
                "@type": "ImageObject",
                "url": "https://thedigitalfrontier.ai/lovable-uploads/2486421b-6ca3-4c32-b686-a49ac0da182b.png"
              }
            },
            "mainEntityOfPage": {
              "@type": "WebPage",
              "@id": "https://thedigitalfrontier.ai/ai-and-digital-marketing"
            }
          })}
        </script>
      </Helmet>
      
      <div className="mb-6">
        <p className="text-slate-300">
          Artificial Intelligence is fundamentally reshaping how we approach digital marketing. From predictive analytics 
          to personalized content generation, AI technologies are enabling marketers to create more effective, 
          efficient, and ethical campaigns that deliver superior results.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {aiMarketingAreas.map((item) => (
          <Link to={item.link} key={item.id}>
            <Card className="bg-slate-800/80 border-slate-700 hover:border-[#00BFFF] transition-colors group h-full">
              <CardHeader className="pb-2">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-slate-700/50 rounded-md group-hover:bg-[#00BFFF]/20 transition-colors">
                    {item.icon}
                  </div>
                  <CardTitle className="text-lg text-slate-100 group-hover:text-[#00BFFF] transition-colors">
                    {item.title}
                  </CardTitle>
                </div>
              </CardHeader>
              <CardContent>
                <p className="text-slate-300 mb-3">{item.description}</p>
                <CardDescription className="text-slate-400 mb-2">
                  <span className="font-semibold text-blue-400">Example:</span> {item.example}
                </CardDescription>
                <CardDescription className="text-slate-400">
                  <span className="font-semibold text-emerald-400">Impact:</span> {item.benefit}
                </CardDescription>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>
      
      <div className="mt-8 p-6 bg-slate-800/60 border border-slate-700 rounded-xl">
        <h3 className="text-xl font-semibold text-[#00BFFF] mb-3">The Future of AI-Driven Marketing</h3>
        <p className="text-slate-300 mb-4">
          As AI technologies continue to evolve, we're seeing unprecedented opportunities for marketers to create 
          more personalized, effective, and ethical campaigns. The key to success lies in understanding both the 
          technical capabilities and the strategic implications of AI implementation.
        </p>
        <p className="text-slate-300 mb-4">
          Companies that embrace AI-driven marketing strategies while maintaining ethical standards and focusing on 
          genuine customer value will emerge as leaders in the digital marketplace of tomorrow.
        </p>
        
        <div className="flex flex-wrap justify-center gap-4 mt-6">
          <Link to="/ad-funnel-blueprint" className="px-4 py-2 bg-blue-600/30 hover:bg-blue-600/50 rounded-md text-blue-300 transition-colors">
            Start with AI Ad Funnels
          </Link>
          <Link to="/generative-engine-optimization" className="px-4 py-2 bg-purple-600/30 hover:bg-purple-600/50 rounded-md text-purple-300 transition-colors">
            Explore GEO
          </Link>
          <Link to="/resources/content-creation-agent" className="px-4 py-2 bg-green-600/30 hover:bg-green-600/50 rounded-md text-green-300 transition-colors">
            Content Creation Tools
          </Link>
        </div>
      </div>
    </PageLayout>
  );
};

export default AIAndDigitalMarketing;
